### ISSUE TITLE
Deprecated use of Ember global

### ISSUE THREAD

**Issue by gitKrystan** [tracked-tools/tracked-built-ins#136]
We are running into the Ember Global deprecation using tracked-built-ins.

#98 resolves this issue in this package, but is not yet released.

https://github.com/pzuraq/tracked-maps-and-sets/issues/80 needs to be resolved as well.

**Comment by pzuraq** [comment]
`tracked-maps-and-sets` has been updated and a new major version has been released. I could use help updating this library as well, for reference anyone who wants to take this on can look at this PR in `tracked-maps-and-sets`: https://github.com/pzuraq/tracked-maps-and-sets/pull/103

The updates in this lib will be pretty similar conceptually, essentially rather than using `notifyPropertyChange` in any way we can now just manually create, entangle, and notify storages when values change.

**Comment by chriskrycho** [comment]
Fixed via v2.0.0!
