### ISSUE TITLE
Unexpected pass-through to glimmer tracked with `@tracked`

### ISSUE THREAD

**Issue by gossi** [tracked-tools/tracked-built-ins#225]
So, today I had this case:

```ts
import { tracked } from 'tracked-built-ins';

class Queue {
  @tracked files = [];

  update() {
    this.files.push('...');
  }
}
```

vs

```ts
import { TrackedArray } from 'tracked-built-ins';

class Queue {
  files = new TrackedArray([]);

  update() {
    this.files.push('...');
  }
}
```

and an `#each` in the template to it:

```hbs
{{#each queue.files as |file|}}
  ...
{{/each}}
```

In both cases I'd expect the `{{#each}}` part to be updated once `update()` is called. However, the first case did nothing, the latter one worked.

Looking into the code, the decorator usage does a passthrough to glimmer's tracked:

https://github.com/tracked-tools/tracked-built-ins/blob/57a813cbdafdf75bded5b8ebc9e1cb17e4443cf2/addon/-private/decorator.ts#L42-L44

My expectation is, that whenever `@tracked` from `tracked-built-ins` is able to recognize one of the supported values, than this is used. If not a fallback to glimmers `@tracked` is used.

Is my assumption correct?

**Comment by chriskrycho** [comment]
This is as expected and indeed exactly as documented. When you use `tracked` from this library as a decorator, it lets you use it as a passthrough (as you found) so that you don't have to import from both this library *and* `@glimmer/tracking`. So in your first example, all you're doing is exactly the same thing you would do by writing `@tracked files = []` with "vanilla" `@tracked`. If you want it to match the second example, you need to flip it: `files = tracked([])`. And of course you could combine them if you had a good reason to.

The distinction between tracking a property which contains an array and creating a `TrackedArray` is extremely significant, so we don't ever want it to be ambiguous which you're doing.
